import React, { useState, useEffect } from 'react';
import { Layout } from './components/Layout';
import { Dashboard } from './views/Dashboard';
import { MinistryDetail } from './views/MinistryDetail';
import { Upload } from './views/Upload';
import { INITIAL_RECORDS } from './data';
import { ViewConfig, Record } from './types';

function App() {
  const [viewConfig, setViewConfig] = useState<ViewConfig>({ view: 'dashboard' });
  const [records, setRecords] = useState<Record[]>(INITIAL_RECORDS);
  const [isLoading, setIsLoading] = useState(true);

  // Auto-fetch data on startup
  useEffect(() => {
    const fetchData = async () => {
      try {
        // Attempt to fetch the file generated by the backend scraper
        const response = await fetch('/data.json');
        if (!response.ok) {
          throw new Error('Data file not found');
        }
        const data = await response.json();
        
        if (Array.isArray(data) && data.length > 0) {
          setRecords(data);
        }
      } catch (error) {
        console.log('Auto-fetch failed or no data present. Falling back to manual mode.');
        // We stay with INITIAL_RECORDS (empty)
      } finally {
        setIsLoading(false);
      }
    };

    fetchData();
  }, []);

  const handleNavigate = (view: 'dashboard' | 'upload') => {
    setViewConfig({ view });
    window.scrollTo(0, 0);
  };

  const handleMinistryClick = (ministryName: string) => {
    setViewConfig({ view: 'ministry', ministryName });
    window.scrollTo(0, 0);
  };

  const handleDataLoaded = (newRecords: Record[]) => {
    setRecords(newRecords);
    handleNavigate('dashboard');
  };

  return (
    <Layout activeView={viewConfig.view} onNavigate={handleNavigate}>
      {viewConfig.view === 'dashboard' && (
        <Dashboard 
          records={records} 
          isLoading={isLoading}
          onMinistryClick={handleMinistryClick} 
          onUploadRequest={() => handleNavigate('upload')}
        />
      )}
      
      {viewConfig.view === 'ministry' && viewConfig.ministryName && (
        <MinistryDetail 
          ministryName={viewConfig.ministryName} 
          records={records}
          onBack={() => handleNavigate('dashboard')}
        />
      )}

      {viewConfig.view === 'upload' && (
        <Upload onDataLoaded={handleDataLoaded} />
      )}
    </Layout>
  );
}

export default App;