import React, { useState } from 'react';
import { Upload as UploadIcon, FileJson, CheckCircle, AlertCircle, AlertTriangle } from 'lucide-react';
import { Record } from '../types';

interface UploadProps {
  onDataLoaded: (data: Record[]) => void;
}

export const Upload: React.FC<UploadProps> = ({ onDataLoaded }) => {
  const [isDragging, setIsDragging] = useState(false);
  const [status, setStatus] = useState<'idle' | 'processing' | 'error'>('idle');
  const [errorMessage, setErrorMessage] = useState('');

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files[0];
    if (file) processFile(file);
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) processFile(file);
  };

  const processFile = (file: File) => {
    if (!file.name.endsWith('.json')) {
      setStatus('error');
      setErrorMessage('Please upload a .json file generated by the scraper script.');
      return;
    }

    setStatus('processing');
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const text = e.target?.result as string;
        const data = JSON.parse(text);

        if (!Array.isArray(data)) {
          throw new Error("File content is not an array");
        }

        // Basic validation
        const isValid = data.every(item => 
          item.ministry && 
          item.vendor && 
          typeof item.amount === 'number'
        );

        if (!isValid) {
          throw new Error("Invalid data structure. Missing required fields.");
        }

        // Success - add slight delay for UX
        setTimeout(() => {
            onDataLoaded(data as Record[]);
        }, 800);
        
      } catch (err) {
        setStatus('error');
        setErrorMessage('Failed to parse JSON file. Ensure it is formatted correctly.');
        console.error(err);
      }
    };

    reader.onerror = () => {
      setStatus('error');
      setErrorMessage('Error reading file.');
    };

    reader.readAsText(file);
  };

  return (
    <div className="max-w-2xl mx-auto animate-fadeIn">
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold text-white mb-2">Import Data</h1>
        <p className="text-gw-muted">Upload the <code>govwatch_data.json</code> file generated from the scraper.</p>
      </div>

      <div 
        className={`bg-gw-card border-2 border-dashed rounded-xl p-12 text-center transition-all duration-200 ${
          isDragging 
            ? 'border-gw-success bg-gw-success/5' 
            : status === 'error' ? 'border-gw-danger'
            : 'border-gw-border'
        }`}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
      >
        {status === 'idle' && (
          <>
            <div className="bg-gw-bg w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 border border-gw-border">
              <UploadIcon className="w-8 h-8 text-gw-muted" />
            </div>
            <h3 className="text-lg font-medium text-white mb-2">Drag and drop your JSON file</h3>
            <p className="text-gw-muted text-sm mb-6">Or click below to browse</p>
            
            <input 
              type="file" 
              id="file-upload" 
              className="hidden" 
              accept=".json"
              onChange={handleFileSelect}
            />
            <label 
              htmlFor="file-upload"
              className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-gw-bg bg-gw-success hover:bg-gw-success/90 cursor-pointer transition-colors"
            >
              Select File
            </label>
            <div className="mt-4 flex items-center justify-center gap-2 text-xs text-gw-muted opacity-60">
                <FileJson className="w-3 h-3" />
                <span>Supports .json format only</span>
            </div>
          </>
        )}

        {status === 'processing' && (
          <div className="py-8">
            <div className="w-12 h-12 border-4 border-gw-success border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-gw-text font-medium">Processing Data...</p>
            <p className="text-sm text-gw-muted mt-2">Validating records structure...</p>
          </div>
        )}

        {status === 'error' && (
          <div className="py-8 animate-fadeIn">
            <div className="w-16 h-16 bg-gw-danger/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <AlertTriangle className="w-10 h-10 text-gw-danger" />
            </div>
            <h3 className="text-xl font-bold text-white mb-2">Upload Failed</h3>
            <p className="text-gw-danger mb-6">{errorMessage}</p>
            <button 
                onClick={() => setStatus('idle')}
                className="text-gw-text hover:text-white underline text-sm"
            >
                Try again
            </button>
          </div>
        )}
      </div>

      <div className="mt-8 bg-gw-card/50 border border-gw-border rounded-lg p-6">
        <h4 className="font-bold text-white mb-2 flex items-center gap-2">
            <AlertCircle className="w-4 h-4 text-gw-muted" />
            How to get data?
        </h4>
        <ol className="text-sm text-gw-muted leading-relaxed list-decimal list-inside space-y-2 mt-3">
            <li>Go to <a href="https://myprocurement.treasury.gov.my/results/tender" target="_blank" className="text-gw-success hover:underline">myprocurement.treasury.gov.my</a></li>
            <li>Open Developer Tools (F12) and go to the <strong>Console</strong> tab.</li>
            <li>Copy and paste the code from <code>scraper.js</code> provided in this project.</li>
            <li>The script will auto-download a JSON file.</li>
            <li>Upload that file here.</li>
        </ol>
      </div>
    </div>
  );
};
